spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unclejet/spring-cloud-config.git
          username: unclejet@126.com
          password: xxx
          search-paths: SC-BOOK-CONFIG
          force-pull: true
  application:
    name: ch12-7-config-server-auth-jwt

  security:
    user:
      name: root
      password: 123

server:
    port: 9090
