spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unclejet/spring-cloud-config.git
          username: unclejet@126.com
          password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: sc-config-git
server:
    port: 9090