server:
  port: 8888
spring:
  application:
    name: spring-cloud-gateway


#spring:
  cloud:
    gateway:
      routes:
      - id: remoteaddr_route
        uri: http://baidu.com
        predicates:
        - RemoteAddr=localhost
