server:
  port: 8887
spring:
  application:
    name: spring-cloud-gateway

#spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://localhost:8071/test/head
        predicates:
        - Header=X-Request-Id, xujin