spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unclejet/{application}
          username: unclejet@126.com
          password: xxx
          search-paths: SC-BOOK-CONFIG
  application:
    name: ch12-1-config-server-placeholders
server:
    port: 9090
logging:
  level:
    root: debug
