spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unclejet/spring-cloud-config.git
          username: unclejet@126.com
          password: xxx
          search-paths: SC-BOOK-CONFIG
  application:
    name: ch12-5-config-server
server:
    port: 9090
